require("config.lazy")

require("cool_bassi.nvim-notify")
require("cool_bassi.treesitter")
require("cool_bassi.lsp")
require("cool_bassi.telescope")
require("cool_bassi.autopairs")
require("cool_bassi.comment")
require("cool_bassi.gitsigns")
require("cool_bassi.nvim-tree")
require("cool_bassi.lualine")
require("cool_bassi.indent-blankline")
require("cool_bassi.toggleterm")
require("cool_bassi.neotest")
require("cool_bassi.markdown-preview")
require("cool_bassi.illuminate")
