require("indent_blankline").setup {
  filetype_exclude = {
    "checkhealth",
    "alpha",
    "help",
    "lazy",
    "lspinfo",
    "man",
    "NvimTree",
    "startify",
    "",
    -- "neogitstatus",
    -- "text",
    -- "Trouble",
  },
  use_treesitter = true,
  use_treesitter_scope = true,
  -- show_current_context = true,
  show_first_indent_level = false,
  show_trailing_blankline_indent = false,
}
